# Site settings
title: Alpha Johnny - Learning to Trade - Basics to Advanced
email: ajay@malhotra.ca
author: Ajay malhotra
description:
url: https://alphajohnny.com
theme: jekyll-theme-slate
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

# Build settings
permalink: :title/
sass:
  sass_dir: css
